// Code generated by Kitex v0.4.4. DO NOT EDIT.

package interactservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	interact "github.com/hcdoit/tiktok/kitex_gen/interact"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FavoriteAction(ctx context.Context, req *interact.FavoriteActionRequest, callOptions ...callopt.Option) (r *interact.FavoriteActionResponse, err error)
	GetFavoriteList(ctx context.Context, req *interact.FavoriteListRequest, callOptions ...callopt.Option) (r *interact.FavoriteListResponse, err error)
	CommentAction(ctx context.Context, req *interact.CommentActionRequest, callOptions ...callopt.Option) (r *interact.CommentActionResponse, err error)
	GetCommentList(ctx context.Context, req *interact.CommentListRequest, callOptions ...callopt.Option) (r *interact.CommentListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractServiceClient struct {
	*kClient
}

func (p *kInteractServiceClient) FavoriteAction(ctx context.Context, req *interact.FavoriteActionRequest, callOptions ...callopt.Option) (r *interact.FavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FavoriteAction(ctx, req)
}

func (p *kInteractServiceClient) GetFavoriteList(ctx context.Context, req *interact.FavoriteListRequest, callOptions ...callopt.Option) (r *interact.FavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFavoriteList(ctx, req)
}

func (p *kInteractServiceClient) CommentAction(ctx context.Context, req *interact.CommentActionRequest, callOptions ...callopt.Option) (r *interact.CommentActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, req)
}

func (p *kInteractServiceClient) GetCommentList(ctx context.Context, req *interact.CommentListRequest, callOptions ...callopt.Option) (r *interact.CommentListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCommentList(ctx, req)
}
