// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	handler "github.com/hcdoit/tiktok/cmd/api/biz/handler"
	"github.com/hcdoit/tiktok/pkg/errno"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) {
		c.JSON(consts.StatusNotFound, errno.ResourceNotFound)
	})
	r.NoMethod(func(ctx context.Context, c *app.RequestContext) {
		c.JSON(consts.StatusInternalServerError, errno.ServiceErr)
	})
}
