// Code generated by hertz generator.

package Api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hcdoit/tiktok/cmd/api/biz/mw"
	"github.com/hertz-contrib/requestid"
	"go.opentelemetry.io/otel/trace"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{

		// use requestid mw
		requestid.New(
			requestid.WithGenerator(func(ctx context.Context, c *app.RequestContext) string {
				traceID := trace.SpanFromContext(ctx).SpanContext().TraceID().String()
				return traceID
			}),
		),
	}
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _comment_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.TokenMiddlewareFunc(),
	}
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorite_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.TokenMiddlewareFunc(),
	}
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavoritelistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.TokenMiddlewareFunc(),
	}
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfeedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publish_ctionMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.TokenMiddlewareFunc(),
	}
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublishlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.TokenMiddlewareFunc(),
	}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
